services:

  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - data:/data/db
      - ./backend/data:/data
    ports:
      - "27017:27017" 
    networks:
      - private

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5000:5000"  
    depends_on:
      - mongodb
    networks:
      - private
      - public

  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./frontend/.env.sample
    ports:
      - "5173:5173"
    depends_on:
      backend:
       condition: service_started
    networks:
      - public

volumes:
  data:
  
networks:
  public: {}
  private: {}
